---
- name: install postgresql
  dnf:
    name: postgresql-server
    state: latest

- name: install postgresql-contrib
  dnf:
    name: postgresql-contrib
    state: latest

- name: get pgsql version
  shell: "psql -V | awk '{print $3}' | cut -b -2"
  register: pgsql_version

- name: initdb
  shell: "sudo -u postgres postgresql-setup --initdb"

- name: enable postgresql service
  service:
    name: postgresql
    state: started
    enabled: true

- name: make listen pgsql server all addresses
  replace:
    path: "{{ pg_data_dir }}/postgresql.conf"
    regexp: "#listen_addresses = 'localhost'"
    replace: "listen_addresses = '*'"

- name: open pg port ufw
  community.general.ufw:
    rule: allow
    port: "{{ pg_port }}"
    proto: tcp
  ignore_errors: true

- name: open pg port iptables
  iptables:
    destination_port: "{{ pg_port }}"
    chain: INPUT
    jump: ACCEPT
    protocol: tcp
  ignore_errors: true

- name: open pg port firewalld
  ansible.posix.firewalld:
    port: "{{ pg_port }}/tcp"
    state: "enabled"
    immediate: true
    permanent: true
  ignore_errors: true

- name: copy config
  template:
    src: "pg_hba.conf.j2"
    dest: "{{ pg_data_dir }}/pg_hba.conf"
    owner: postgres
    group: postgres
    mode: 0600
  notify: restart postgres

- name: run handlers
  meta: flush_handlers

- name: create user and give all privileges
  shell: |
    psql -U postgres -c "CREATE USER {{ user }} WITH PASSWORD '{{ password }}';"
